---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles

collections:
  - name: geerlingguy.mac
  - name: community.general
    version: ">=5.5.0"  # pipx module added in 3.8.0, but state: latest requires 5.5.0
